/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSkeletonPulse: typeof import('./src/components/common/AppSkeletonPulse.vue')['default']
    BookingFilter: typeof import('./src/components/admin/BookingFilter.vue')['default']
    BookingForm: typeof import('./src/components/booking/BookingForm.vue')['default']
    BookingStats: typeof import('./src/components/admin/BookingStats.vue')['default']
    BookingTable: typeof import('./src/components/admin/BookingTable.vue')['default']
    CtaSection: typeof import('./src/components/home/CtaSection.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    HeroCarousel: typeof import('./src/components/home/HeroCarousel.vue')['default']
    LocationSection: typeof import('./src/components/home/LocationSection.vue')['default']
    ReviewCard: typeof import('./src/components/home/ReviewCard.vue')['default']
    ReviewForm: typeof import('./src/components/home/ReviewForm.vue')['default']
    ReviewSection: typeof import('./src/components/home/ReviewSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceAiHelper: typeof import('./src/components/common/ServiceAiHelper.vue')['default']
    ServiceCard: typeof import('./src/components/home/ServiceCard.vue')['default']
    ServiceDetailCard: typeof import('./src/components/services/ServiceDetailCard.vue')['default']
    ServiceFilter: typeof import('./src/components/services/ServiceFilter.vue')['default']
    ServiceList: typeof import('./src/components/services/ServiceList.vue')['default']
    ServiceSection: typeof import('./src/components/home/ServiceSection.vue')['default']
    ServiceSelector: typeof import('./src/components/booking/ServiceSelector.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TimePicker: typeof import('./src/components/booking/TimePicker.vue')['default']
    WhyChooseSection: typeof import('./src/components/home/WhyChooseSection.vue')['default']
  }
}
